# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - rm wipy.dmg
      - appdmg wipy.json wipy.dmg
      - poetry run python deploy.py
    silent: true
